# Rails:
#   Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Severity: refactor
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 500
Metrics/ParameterLists:
  Max: 10
Metrics/BlockNesting:
  Max: 4
